
spring.datasource.url=jdbc:mariadb://localhost:3306/tutorias_luiggi_7502120036
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080


jwt.secret=MiSecretoUltraSecreto1234567890LuiggiSalemi7502120036
jwt.expiration.ms=86400000
